import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "../components/layout/header";
import { AudioProvider } from "../components/providers/audio-provider";
import { Footer } from "../components/layout/footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-[var(--color-gray-lighter)]">
        <AudioProvider>
          <Header />
          <div className="layout">{children}</div>
        </AudioProvider>
        <Footer />
      </body>
    </html>
  );
}
